# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: PI Unmasked
email: piunmasked@gmail.com
repository: "pi-unmasked/pi_unmasked"
url: "www.pi-unmasked.com" # the base hostname & protocol for your site
github_username: pi-unmasked
teaser: /assets/images/glycans.png
logo: "/assets/images/fucose.png"
description: "A site for students and post-doc interested in a particular research lab"
words_per_minute: 200
include: ["_pages"]
defaults:
 # _pages
 - scope:
     path: ""
     type: pages
   values:
     layout: single

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.19.2"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
